FROM node:22-alpine
WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./
COPY packages/crawlers packages/crawlers
COPY packages/db packages/db
RUN corepack enable && pnpm install --frozen-lockfile
CMD ["pnpm", "--filter", "@openquebec/crawlers", "start"]
